version: '3'
env:
  README_YAML: "{{.ROOT_DIR}}/README.yaml"
  README_INCLUDES: ""


vars:
  README_TEMPLATE_FILE: "{{.PATH}}/templates/README.md.gotmpl"
  README_TEMPLATE_YAML: "{{.PATH}}/templates/README.yaml"
  README_FILE: "{{.ROOT_DIR}}/README.md"

tasks:
  install:
    cmds:
      - task packages:gomplate:install
  build:
    desc: "Build README"
    silent: true
    cmds:
       - |
         {{.GOMPLATE}} --file {{.README_TEMPLATE_FILE}}  --out {{.README_FILE}}
       - MESSAGE="Generated {{.README_FILE}} from {{.README_TEMPLATE_FILE}}" task utils:print_info