version: '3'
env:
  README_YAML: "{{.ROOT_DIR}}/README.yaml"
  README_INCLUDES: ""


vars:
  README_TEMPLATE_FILE: "{{.PATH}}/templates/README.md.gotmpl"
  README_TEMPLATE_YAML: "{{.PATH}}/templates/README.yaml"
  README_FILE: "{{.ROOT_DIR}}/README.md"

tasks:
  install:
    cmds:
      - task packages:gomplate:install
  build:
    desc: "Build README"
    silent: true
    deps:
      - task: install
    cmds:
       - |
         {{.GOMPLATE}} --file {{.README_TEMPLATE_FILE}}  --out {{.README_FILE}}
       - MESSAGE="Generated {{.README_FILE}} from {{.README_TEMPLATE_FILE}}" task utils:print_info
  build:referances:
    desc: "Build README referances"
    silent: true
    cmds:
      - |
        task packages:python:pip:install PYTHON_PACKAGE=requests
        task packages:python:pip:install PYTHON_PACKAGE=PyGithub
        task packages:python:pip:install PYTHON_PACKAGE=iteration_utilities
        task packages:python:pip:install PYTHON_PACKAGE=ruamel.yaml
        task packages:python:run SCRIPT="{{.PATH}}/bin/generate_related_referances.py"