version: '3'
includes:
  readme:
    taskfile: ./modules/readme/Taskfile.yaml
    optional: true
  terraform:
    taskfile: ./modules/terraform/Taskfile.yaml
    optional: true
vars:
  OS:
    sh: uname -s | tr '[:upper:]' '[:lower:]'
  BUILD_HARNESS_ARCH:
    sh: uname -m | sed 's/x86_64/amd64/g'
  BUILD_HARNESS_PATH:
    sh: |
      if [ ! -z ${BUILD_HARNESS_PATH} ]; then
        echo "${BUILD_HARNESS_PATH}"
      else
        echo "{{.ROOT_DIR}}"
      fi
  BUILD_HARNESS_OS:
    sh: echo "{{.OS}}"
tasks:
  default:
    cmds:
      - cat {{.BUILD_HARNESS_PATH}}/logo.txt
      - task --list-all
    silent: true
    desc: "Usage description"
