version: '3'
includes:
  readme:
    taskfile: ./modules/readme/Taskfile.yaml
    optional: true
  terraform:
    taskfile: ./modules/terraform/Taskfile.yaml
    optional: true
  utils:
    taskfile: ./modules/utils/Taskfile.yaml
    optional: true
vars:
  OS:
    sh: uname -s | tr '[:upper:]' '[:lower:]'
  ARCH:
    sh: uname -m | sed 's/x86_64/amd64/g'
  PATH:
    sh: |
      if [ "{{.BUILD_HARNESS_PATH}}" != "" ]; then
        echo {{.BUILD_HARNESS_PATH}}
      else
        echo {{.ROOT_DIR}}
      fi
tasks:
  default:
    cmds:
      - task: help
  help:
    cmds:
      - cat {{.PATH}}/logo.txt
      - task --list
    silent: true
    desc: "Build harness help"
