version: '3'
vars:
  CURRENT_TIME:
    sh: date +'%Y-%m-%d %H:%m:%S'
tasks:
  print_info:
    cmds:
      - echo "======================================================================"
      - echo "{{.CURRENT_TIME}} [INFO] - {{.MESSAGE}}"
      - echo "======================================================================"
    silent: true
  print_error:
    cmds:
      - echo "{{.CURRENT_TIME}} [ERROR] - {{.MESSAGE}}"
  print_debug:
    cmds:
      - echo "{{.CURRENT_TIME}} [DEBUG] - {{.MESSAGE}}"
